Fixed flaw in case jflex.jar is in the CLASSPATH

diff --git a/tools/bin/jflex b/tools/bin/jflex
--- a/tools/bin/jflex
+++ b/tools/bin/jflex
@@ -2,15 +2,20 @@
 
 if [ -f /usr/share/java/java_cup-runtime.jar ]; then
 	CUP=/usr/share/java/java_cup-runtime.jar
+	CLASSPATH=$CUP:$CLASSPATH
 fi
 
 if ! echo $CLASSPATH | grep -i jflex >/dev/null 2>&1; then
 	echo "WARNING: Didn't find jflex.jar or similar in CLASSPATH"
 	# The next will do an educated guess (which works on several Linux)
 	if [ -d /usr/share/java ]; then
-		X=`ls /usr/share/java/[Jj][Ff]lex* 2>/dev/null | head -1`:$CUP
+		X=`ls /usr/share/java/[Jj][Ff]lex* 2>/dev/null | head -1`
 		if [ $? -eq 0 ]; then
 			export CLASSPATH=$X:$CLASSPATH
+		else
+			echo "ERROR: I didn't find a jflex.jar or JFlex.jar in /usr/share/java"
+			echo "       If the jflex jarfile is stored somewhere else, please add it to your CLASSPATH"
+			exit 1
 		fi
 	fi
 fi
