rpm development wip

diff --git a/bin/setup_jobserver b/bin/setup_jobserver
--- a/bin/setup_jobserver
+++ b/bin/setup_jobserver
@@ -50,7 +50,7 @@
 
 usage()
 {
-	echo "Usage: $0 [-h] [-n JSNAME] [-w JSPWD] [-o OWNER] [-H SDMSHOST] [-P SDMSPORT] [-w JSWD] [-c] [-u SDMSUSER] [-p SDMSPWD]"
+	echo "Usage: $0 [-h] [-n JSNAME] [-w JSPWD] [-o OWNER] [-H SDMSHOST] [-P SDMSPORT] [-h HTTPPORT] [-w JSWD] [-c] [-u SDMSUSER] [-p SDMSPWD]"
 	echo "JSNAME   is the name of the jobserver to create"
 	echo "JSPWD    is the password of the jobserver to create"
 	echo "OWNER    is the owner group of the jobserver to create"
@@ -59,6 +59,7 @@ usage()
 	echo "JSWD     is the working directory of the jobserver"
 	echo "SDMSUSER is the username of the admin user that creates the jobserver within schedulix"
 	echo "SDMSPWD  is the password of SDMSUSER"
+	echo "HTTPPORT is the port that is used for logfile display"
 	echo "-c       this flag tries to create the jobserver's working directory if it doesn't exist"
 	echo "-h       gives this message"
 }
@@ -73,6 +74,7 @@ outputConfig()
 	echo "JSWD     = '$JSWD'"
 	echo "SDMSUSER = '$SDMSUSER'"
 	echo "SDMSPWD  = '$SDMSPWD'"
+	echo "HTTPPORT = '$HTTPPORT'"
 	echo "-c       = '$CREATEWD'"
 }
 
@@ -237,6 +239,8 @@ while [ -n "$1" ]; do
 		shift ;;
 	-H)	SDMSHOST=$2 ;
 		shift ;;
+	-h)	HTTPPORT=$2 ;
+		shift ;;
 	-P)	SDMSPORT=$2 ;
 		shift ;;
 	-w)	JSWD="$2" ;
@@ -311,19 +315,44 @@ RepoUser= \"$FQJSNAME\"
 RepoPass= \"$JSPWD\"
 " >> $HOME/etc/$JSNAME.conf
 
-# 3. create loggin directory
+# 3. create logging directory
 mkdir -p $HOME/log
 
-# calculate some httpport for logfile view
-MYEUID=`id -u`
-HTTPPORT=`expr 10 * $MYEUID + 10240`
-while netstat -an | grep $HTTPPORT; do
-	HTTPPORT=`expr $HTTPPORT + 1`
-	if [ $HTTPPORT -gt 65535 ]; then
-		echo "ERROR: couldn't find a suitable httpport for logfile view"
-		exit 1
+# 4. add source of SETTINGS to .bashrc
+if [ -f ~/.bashrc ]; then
+	if ! grep 'schedulix/etc/SETTINGS'  ~/.bashrc >/dev/null 2>&1; then
+		echo ". /opt/schedulix/etc/SETTINGS" >> ~/.bashrc
 	fi
-done
+else
+	echo ". /opt/schedulix/etc/SETTINGS" >> ~/.bashrc
+fi
+
+# calculate some httpport for logfile view
+if [ -z "$HTTPPORT" ]; then
+	MYEUID=`id -u`
+	HTTPPORT=`expr 10 '*' $MYEUID`
+	HTTPPORT=`expr $HTTPPORT + 10240`
+	while netstat -an | grep $HTTPPORT; do
+		HTTPPORT=`expr $HTTPPORT + 1`
+		if [ $HTTPPORT -gt 65535 ]; then
+			echo "ERROR: couldn't find a suitable httpport for logfile view" >&2
+			exit 1
+		fi
+	done
+else
+	if netstat -an | grep $HTTPPORT; then
+		echo "The specified HTTPPORT ($HTTPPORT) seemst to be in use" >&2
+		echo "The jobserver will be configured without HTTPPORT" >&2
+		HTTPPORT=''
+	fi
+fi
+if [ -n "$HTTPPORT" ]; then
+	echo "The HTTPPORT that will be used for logfile display is $HTTPPORT"
+	echo "This can be changed at any time in the config tab of the jobserver"
+	HTTPOPTION=", HTTPPORT = '$HTTPPORT'"
+else
+	HTTPOPTION=''
+fi
 
 echo "
 whenever error disconnect 1;
@@ -341,6 +370,7 @@ with
 		'JOBEXECUTOR' = '$BICSUITEHOME/bin/jobexecutor',
 		'DEFAULTWORKDIR' = '$JSWD',
 		'VERBOSELOGS' = 'true',
+		'HTTPHOST' = '$HOSTNAME',
 		'NAME_PATTERN_LOGFILES' = '.*\\.log',
 		'ENV' = (
 			'SDMSHOST' = 'SDMSHOST',
@@ -352,10 +382,7 @@ with
 
 create or alter scope $FQSCOPE2
 with
-	group = 'PUBLIC',
-	config = (
-		'HTTPHOST' = '$HOSTNAME'
-	);
+	group = 'PUBLIC';
 
 create or alter job server $FQJSNAME
 with
@@ -363,8 +390,8 @@ with
 	password = '$JSPWD',
 	node = '$HOSTNAME',
 	config = (
-		'JOBFILEPREFIX' = '${TFDIR}/${JSNAME}-',
-		'HTTPPORT' = '$HTTPPORT'
+		'JOBFILEPREFIX' = '${TFDIR}/${JSNAME}-'
+		$HTTPOPTION
 	);
 
 create or alter named resource RESOURCE.'STATIC'
